.gitignore
basic_bot.js

most errors are now gone. code is pretty :)

Linted and dank

---

.gitignore
basic_bot.js

Revert "Linted and dank"

---

.gitignore
basic_bot.js

Revert "Revert "Linted and dank""

---

.gitignore
basic_bot.js

Revert "Revert "Revert "Linted and dank"""

---

.gitignore
basic_bot.js

Revert "Revert "Revert "Revert "Linted and dank""""

---

README.md

Resizing readme images

---

.gitignore
src/bot.js
src/helpers/finders.js
src/helpers/map.js
src/helpers/player.js
src/index.js
tests/map.spec.js
webpack.config.js

I went in and addressed some of the changes I requested. Also `npm run build:test` was broken, I fixed it

17: Addressing some PR changes

---

src/helpers/map.js
tests/map.spec.js
webpack.config.js

Fixes #55 and fixes #59 
Changes
- Made lines shorter
- Previously when webpack was running tests, it was not transpiling the files it was testing. Now, it is.

55: hotfix

---

.travis.yml
package.json

Closes #69 
We now have continuous integration with Travis CI!  This means that whenever you push something to github, your code gets uploaded to Travis and they will run the linter and the tests and make sure they all pass for your code.
When you see your commits (i.e. in a PR) you'll see a little icon, which corresponds to a Travis status.  Hover over it for more information, but these are what the icons mean:
- **Yellow circle**: Travis is running your stuff, check back in like a minute
- **Green checkmark**: Your tests and linter passed!
- **Red X**: Uh oh, something didn't pass!  Click on me to see the terminal output in Travis to figure out what failed.
Example:

69: Travis CI

---

.travis.yml
README.md

73: Add travis status to readme like a cool repo

---

.babelrc
.eslintrc
package-lock.json
package.json
src/draw/visualizePath.js
test/visualizePath.spec.js

We're using sinon to spy on functions and see if they're called, and we're using Rewire to mock any top-level variables.
use `global.tagpro = 'poop'` to mock the global tagpro object

Path vis tests

---

src/bot.js
src/helpers/path.js

85: separating shortest path and get target into two separaionated functions

---

test/asserts.spec.js
test/map.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/100)

98: Change any unit tests not conforming to the new unit test naming convention

---

test/asserts.spec.js
test/map.spec.js

Closes #98
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/114)

98: unify unit test naming

---

src/helpers/map.js
src/helpers/path.js
test/map.spec.js

Closes #51 
Angled walls are now pixel-perfect (assuming a high enough `CPTL`) in path planning.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/102)

51: Implement diagonal wall functionality in `getTileTraversabilityInCells`

---

src/index.js
src/utils/interface.js

Closes #89
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/120)

89: Send command options to chat at beginning of each game

---

package-lock.json
package.json
src/bot.js
src/draw/drawings.js
src/helpers/finders.js
src/helpers/map.js
src/helpers/path.js
src/utils/interface.js
test/drawings.spec.js
test/path.spec.js

Closes #31 
http://i.imgur.com/oR8crxH.gifv
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/121)

31: Add path planning functionality when CPTL>1

---

package-lock.json
package.json
src/bot.js
src/draw/drawings.js
src/helpers/finders.js
src/helpers/map.js
src/helpers/path.js
src/utils/interface.js
test/drawings.spec.js
test/path.spec.js

Closes #31 
Second time is the charm!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/159)

31: path planning nonunit cptl

---

src/helpers/player.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/145)

115: Remove unused mockMe function

---

src/utils/interface.js

Closes #90
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/148)

90: documenting the setupVelocity function

---

test/asserts.spec.js
test/convolve.spec.js
test/map.spec.js

closes #111
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/149)

111: updating unit test phrasing

---

src/utils/interface.js

Closes #160
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/169)

160: Reformat the chat help menu so it is more clear when it starts and stops

---

test/map.spec.js
test/tiles.spec.js

Closes #143
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/152)

143: changing input to setupTiles to a team color int

---

.eslintrc
package-lock.json
package.json
webpack.config.js

Closes #164
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/165)

164: Change eslintconfig to airbnb-base instead of full airbnb

---

.eslintrc
src/helpers/map.js
test/drawings.spec.js
test/map.spec.js
test/path.spec.js
test/tiles.spec.js

Closes #76
The airbnb config was ignoring strings and some other stuff for the max-len rule.  Now we don't ignore anything anymore, so all lines have to be 100 chars
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/163)

76: Fixing Max-len errors

---

test/draw/drawings.spec.js
test/helpers/convolve.spec.js
test/helpers/finders.spec.js
test/helpers/map.spec.js
test/helpers/path.spec.js
test/utils/asserts.spec.js

Closes #166
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/170)

166: Restructure the test directory to mirror the src directory

---

src/draw/drawings.js
src/helpers/finders.js
src/helpers/path.js
src/tiles.js

closes #146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/151)

146: return types

---

test/convolve.spec.js
test/map.spec.js

Closes #125
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/150)

125: unittest answers inline

---

src/helpers/path.js

closes #161. Code courtesy of @altodyte on my laptop
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/162)

161: adding comments to getTarget

---

reviewable.js

closes #175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/176)

175: fix some indentation, make reviewable reject merges not into master

---

src/utils/interface.js

sorry guys :(
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/168)

90: setup velocity documentation

---

src/index.js

Closes #174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/178)

174: Remove the Tampermonkey header from src/index.js

---

src/bot.js
src/draw/drawings.js
src/index.js
src/utils/interface.js
test/draw/drawings.spec.js

Closes #134
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/179)

134: Allow visuals to be enabled while in manual mode

---

reviewable.js

closes #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/186)

185: mark file as unreviewed unless 2 reviews

---

test/helpers/finders.spec.js

Closes #192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/193)

192: Fix tagpro object mock declaration in test

---

src/utils/interface.js

Closes #173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/194)

173: Make a helper function for bot key presses

---

package-lock.json
package.json
src/bot.js
src/utils/interface.js
test/utils/interface.spec.js

Closes #180
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/195)

180: Command menu can print out of order

---

.travis.yml

Closes #197
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/198)

197: Add Travis Notifications to Slack

---

.babelrc
package-lock.json
package.json
src/helpers/map.js
test/draw/drawings.spec.js
test/helpers/finders.spec.js
test/helpers/map.spec.js
test/helpers/path.spec.js
test/tiles.spec.js

closes #129 
removed setupTiles() and teardownTiles() function, now tests are not dependent on tiles.js functioning properly. If it isn't, only the tests in tiles.js will fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/199)

129: improved tests

---

src/helpers/path.js

I did a small thing, close this if you don't like it
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/208)

200: Bill A* Improvements

---

src/bot.js
src/constants.js
src/draw/drawings.js
src/helpers/constants.js
src/helpers/convolve.js
src/helpers/map.js
src/utils/asserts.js
test/helpers/constants.spec.js
test/helpers/convolve.spec.js
test/helpers/map.spec.js

Closes #124
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/210)

124: apply NT kernel

---

.eslintrc
src/constants.js
src/draw/drawings.js
src/index.js
src/utils/interface.js
test/draw/drawings.spec.js

Closes #154
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/221)

154: visualize keypresses

---

src/navmesh/graph.js
src/navmesh/polygon.js
test/navmesh/polygon.spec.js

closes #214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/224)

214: Convert grid to graph

---

src/bot.js
src/draw/drawings.js
src/helpers/constants.js
src/helpers/convolve.js
src/helpers/finders.js
src/helpers/map.js
src/helpers/path.js
src/index.js
src/tiles.js
src/utils/asserts.js
src/utils/interface.js

Closes #155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/227)

155: change all function-level comments to adhere to JSDoc conventions

---

package-lock.json
src/bot.js
src/constants.js
src/draw/drawings.js
src/helpers/convolve.js
src/helpers/map.js
src/index.js
src/navmesh/triangulation.js
test/draw/drawings.spec.js

Closes #218 
PR into david's branch for review
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/220)

218: Make Drawing API for Edges

---

src/bot.js
src/constants.js
src/draw/drawings.js
src/helpers/constants.js
src/helpers/map.js
src/helpers/path.js
src/helpers/physics.js
src/helpers/player.js
test/draw/drawings.spec.js
test/helpers/path.spec.js
test/helpers/physics.spec.js

closes #229
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/240)

229: capitalize constants

---

src/helpers/path.js

closes #187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/239)

187: add return type to heuristic function

---

src/navmesh/graph.js
src/navmesh/polygon.js
test/draw/drawings.spec.js
test/navmesh/polygon.spec.js

closes #223
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/238)

223: improve runtime of graph using adjacency list

---

.eslintrc
src/constants.js
src/draw/drawings.js
src/helpers/path.js
src/navmesh/graph.js
src/navmesh/polygon.js
src/navmesh/triangulation.js
test/helpers/path.spec.js
test/navmesh/graph.spec.js
test/navmesh/triangulation.spec.js
test/tiles.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/242)

215: delaunay working and tests

---

.eslintrc
src/constants.js
src/draw/drawings.js
src/helpers/path.js
src/navmesh/graph.js
src/navmesh/polygon.js
src/navmesh/triangulation.js
src/utils/interface.js
test/draw/drawings.spec.js
test/helpers/path.spec.js
test/navmesh/graph.spec.js
test/navmesh/triangulation.spec.js
test/tiles.spec.js

Closes #215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/247)

215: Perform Delaunay Triangulation on Map Vertices

---

src/draw/drawings.js

Closes #254
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/255)

254: [HOT FIX] visualizations for triangulation doesnt toggle

---

src/draw/drawings.js
test/draw/drawings.spec.js

closes #257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/258)

257: mock foreground in drawing test

---

src/draw/drawings.js
src/utils/interface.js

Closes #252
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/256)

252: make keypress visualization toggle with other visualizations

---

package.json
src/constants.js
src/draw/drawings.js
src/navmesh/graph.js
src/navmesh/triangulation.js
test/navmesh/triangulation.spec.js

closes #251
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/259)

251: Convert Triangulation Graph class to polypoints

---

.eslintrc
src/bot.js
src/constants.js
src/draw/drawings.js
src/helpers/map.js
src/helpers/path.js
src/navmesh/graph.js
src/navmesh/path.js
test/draw/drawings.spec.js
test/helpers/path.spec.js

closes #202
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/266)

202: Perform A* on Nav Mesh Polypoints

---

src/draw/drawings.js
test/draw/drawings.spec.js

closes #269
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/270)

269: Only use one instance of `PIXI.Graphics` when applicable

---

test/draw/drawings.spec.js

closes #273
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/275)

273: fix TypeError: graphGraphics.lineStyle is not a function

---

src/draw/drawings.js
src/helpers/map.js
test/helpers/map.spec.js

closes #136
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/274)

136: only update visuals for cells that did change, instead of cells that might have changed

---

src/navmesh/graph.js
test/navmesh/graph.spec.js

closes #246.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/276)

246: calculate if fourth point is on circumcircle of other three points using a matrix determinant

---

src/bot.js
src/constants.js
src/draw/drawings.js
src/index.js
test/draw/drawings.spec.js

Closes #248
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/277)

248: visualize estimated enemy path

---

src/bot.js
src/navmesh/triangulation.js
test/navmesh/triangulation.spec.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/291)

285: add third dummy point to initial containing triangle

---

.eslintrc
src/helpers/map.js
src/navmesh/graph.js
src/navmesh/graphUtils.js
src/navmesh/polygon.js
src/navmesh/triangulation.js
test/navmesh/graph.spec.js
test/navmesh/polygon.spec.js
test/navmesh/triangulation.spec.js

Closes #216
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/294)

216: Perform Constrained Delaunay Triangulation

---

src/navmesh/graph.js
src/navmesh/graphUtils.js
src/navmesh/path.js
src/navmesh/polygon.js
test/navmesh/graph.spec.js
test/navmesh/path.spec.js

Closes #261 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/302)

261: Implement Funnel Path-Planning on Polypoints

---

src/navmesh/path.js
test/navmesh/path.spec.js

Closes #303
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/304)

[HOT FIX] 303: Funnel properly when target and start point are in the same triangle

---

src/navmesh/graph.js
src/navmesh/graphUtils.js
src/navmesh/path.js
src/utils/general.js
test/helpers/physics.spec.js
test/navmesh/graphUtils.spec.js
test/navmesh/path.spec.js

Closes #300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/305)

300: Implement Funnel Clearance Algorithm

---

src/bot.js
src/constants.js
src/helpers/fsm.js
src/helpers/path.js
src/utils/general.js
src/utils/geometry.js
test/helpers/path.spec.js

Closes #249
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/306)

249: Find and navigate to interception point with just distance

---

src/bot.js
src/helpers/constants.js
src/helpers/finders.js
src/helpers/fsm.js
src/helpers/player.js
src/index.js

Closes #292
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/308)

292: Make our bot demoable for two-flag games

---

src/bot.js
src/constants.js
src/navmesh/graphUtils.js
src/navmesh/path.js
test/navmesh/graphUtils.spec.js

closes #203
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/313)

203: Motion towards next polypoint along navmesh path

---

src/bot.js
src/draw/drawings.js
src/helpers/finders.js
src/helpers/fsm.js
src/navmesh/path.js
src/utils/fsmUtils.js
test/draw/drawings.spec.js

Closes #312
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/323)

312: Use navmesh to calculate opponent path

---

src/constants.js
src/draw/drawings.js
src/helpers/map.js
src/index.js
src/utils/interface.js
test/draw/drawings.spec.js

closes #290
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/317)

290: Have dedicated buttons to toggle each kind of visualization, and print commands to team-chat.

---

src/navmesh/graph.js
src/navmesh/graphUtils.js
src/navmesh/path.js
test/helpers/path.spec.js
test/helpers/physics.spec.js

Close #264
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/325)

264: change equal to equals

---

src/interpret/class/TriangleGraph.js

Closes #345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/346)

345: Fix odd number of neighbors bug

---

src/interface/chat.js
src/interface/keys.js
src/start.js

Closes #333
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/354)

333: Console.log the help menu instead of sending it to the TagPro team chat

---

src/draw/draw.js
src/draw/keys.js

Closes #338
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/356)

338: remove getPixiSquare()

---

src/draw/keys.js

Closes #336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/357)

336: add KEY_INDICES object for use in draw/keys.js

---

src/interpret/class/Graph.js
src/interpret/class/Point.js
src/interpret/class/TriangleGraph.js
src/interpret/class/test/Graph.spec.js
src/interpret/mapToGraph.js
src/interpret/test/graph.spec.js
src/interpret/utils.js

closes #328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/352)

328: improve runtime of Graph class

---

src/draw/test/triangulation.spec.js
src/draw/triangulation.js
src/interpret/class/Edge.js
src/interpret/class/Graph.js
src/interpret/class/Triangle.js
src/interpret/class/TriangleGraph.js
src/interpret/class/test/Edge.spec.js
src/interpret/class/test/Graph.spec.js
src/interpret/class/test/Triangle.spec.js
src/interpret/class/test/TriangleGraph.spec.js
src/interpret/graphToTriangulation.js
src/interpret/mapToGraph.js
src/interpret/test/graphToTriangulation.spec.js
src/interpret/test/mapToGraph.spec.js
src/interpret/test/setup.spec.js
src/interpret/test/utils.spec.js
src/interpret/utils.js
src/plan/funnel.js

Closes #263
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/355)

263: add edge class

---

src/draw/constants.js
src/draw/keys.js
src/draw/test/triangulation.spec.js
src/draw/triangulation.js

Closes #337
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/359)

337: add colors objects to draw/constants.js

---

src/interpret/class/Edge.js
src/interpret/class/Graph.js
src/interpret/class/Point.js
src/interpret/class/TriangleGraph.js

Closes #358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/360)

358: make getEdges runtime O(E)

---

src/control/physics.js
src/draw/class/DrawableGraph.js
src/draw/class/test/DrawableGraph.spec.js
src/draw/keys.js
src/draw/test/triangulation.spec.js
src/draw/triangulation.js
src/interpret/class/Graph.js
src/interpret/class/TriangleGraph.js
src/interpret/class/test/TriangleGraph.spec.js
src/interpret/graphToTriangulation.js
src/interpret/setup.js
src/interpret/test/setup.spec.js
src/think/fsm.js

Closes #348
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/376)

348: dynamic update vertex drawings

---

src/interface/chat.js
src/start.js

Closes #370
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/381)

370: add chat callback with framework that parses for keywords

---

src/draw/class/DrawableGraph.js
src/draw/class/test/DrawableGraph.spec.js
src/draw/constants.js
src/draw/test/triangulation.spec.js
src/draw/triangulation.js
src/interpret/class/Edge.js
src/interpret/class/Graph.js
src/interpret/class/TriangleGraph.js
src/interpret/class/test/TriangleGraph.spec.js
src/interpret/graphToTriangulation.js

Closes #349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/384)

349: dynamic updates for edge drawings and polypoints

---

src/control/physics.js
src/draw/constants.js
src/draw/triangulation.js
src/think/fsm.js

Closes #350
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/386)

350: add ball thickness to path drawing

---

src/control/physics.js
src/interpret/graphToTriangulation.js
src/plan/astar.js
src/plan/funnel.js
src/start.js

Closes #341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/385)

341: break getAccelValues up into blocks in start.js

---

package-lock.json
package.json
src/control/class/Matrix.js
src/control/class/test/Matrix.spec.js

Closes #390
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/398)

Matrix math functions

---

src/think/fsm.js

Closes #399
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/400)

399: funnel enemy path

---

src/interpret/class/Edge.js
src/interpret/class/Triangle.js
src/interpret/class/test/Edge.spec.js
src/interpret/class/test/Triangle.spec.js
src/interpret/mapToGraph.js
src/interpret/utils.js
src/plan/funnel.js
src/think/fsm.js

Closes #405
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/406)

405 clarify functions

---

src/look/test/gameState.spec.js

Closes #413
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/414)

413: remove test.only from assumeComplementaryRole() unit test

---

src/global/utils.js
src/interpret/setup.js
src/start.js

Closes #403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/415)

403: time stamped logs of the startup sequence

---

simulation/README.md
simulation/src/main.py
simulation/src/physics.py
src/control/class/Matrix.js
src/control/class/test/Matrix.spec.js
src/control/constants.js
src/control/lqr.js
src/control/test/lqr.spec.js

Closes #388
Closes #389 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/416)

388: Generate K-matrices and use them to move

---

src/draw/class/DrawableGraph.js
src/interpret/class/Edge.js
src/interpret/class/Point.js
src/interpret/class/Triangle.js
src/interpret/class/TriangleGraph.js
src/interpret/class/TriangleTreeNode.js
src/interpret/class/test/Edge.spec.js
src/interpret/class/test/Point.spec.js
src/interpret/class/test/Triangle.spec.js
src/interpret/class/test/TriangleGraph.spec.js
src/interpret/class/test/TriangleTreeNode.spec.js
src/interpret/setup.js
src/interpret/test/setup.spec.js
src/interpret/utils.js
src/start.js

Closes #267
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/418)

267 triangle tree

---

src/interface/chat.js
src/look/gameState.js
src/look/playerLocations.js
src/look/playerRoles.js
src/look/setup.js
src/look/test/playerLocations.spec.js
src/look/test/playerRoles.spec.js
src/look/tileLocations.js
src/plan/astar.js
src/start.js
src/think/fsm.js

Closes #391
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/425)

391: defense fsm

---

src/control/physics.js
src/look/playerLocations.js
src/look/tileLocations.js
src/plan/pgp.js
src/think/fsm.js

Closes #393
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/424)

393: PGP Position with no boosts/bombs

---

src/control/lqr.js
src/interpret/class/Point.js
src/start.js

Closes #410
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/429)

410: determine local goal velocity for future use with LQR

---

package-lock.json
package.json
webpack.config.js

Closes #326
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/433)

326: update npm packages

---

src/plan/astar.js

:fire: 
Closes #443
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/444)

443: [HOT FIX] Import FibonacciHeap correctly

---

src/control/lqr.js
src/control/test/lqr.spec.js
src/interpret/class/Point.js

Closes #411
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/437)

411: LQR Deadline

---

src/interpret/setup.js

Closes #450
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/451)

450: add time logs for merged graph and unmerged graph

---

src/control/lqr.js
src/global/class/Point.js
src/global/timing.js
src/global/utils.js
src/interpret/class/TriangleGraph.js
src/interpret/setup.js
src/look/playerRoles.js
src/look/setup.js
src/start.js
src/think/fsm.js

Closes #438
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/445)

438: time all processes in botLoop()

---

src/start.js

Closes #467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/468)

467: Call requestAnimationFrame only after loop is done

---

src/control/lqr.js
src/control/lqr.worker.js
src/start.js

Closes #417
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/469)

417: enable LQR

---

src/control/class/Matrix.js
src/control/lqr.js

Closes #441
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/471)

441: Scale LQR accelerations to a max

---

src/start.js

Closes #476
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/477)

476: requestAnimationFrame even if bot doesn't run

---

src/global/timing.js
src/plan/astar.js
src/plan/constants.js
src/start.js
src/think/fsm.js

Closes #428
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/478)

428: go to alternate goal if current path cost is too high

---

src/control/lqr.js
src/draw/arrow.js
src/draw/constants.js
src/draw/draw.js
src/draw/localGoal.js
src/draw/path.js
src/draw/triangulation.js
src/global/class/Point.js
src/global/class/Vector.js
src/global/class/test/Vector.spec.js
src/global/test/utils.spec.js
src/global/utils.js
src/interface/keys.js
src/start.js

Closes #466
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/chauncy-crib/tagprobot/492)

466: draw local goal velocity
